# Generated by Django 4.1.7 on 2023-05-29 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_watchlist_created_at_alter_watchlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='created_at',
        ),
    ]
