# Generated by Django 4.1.7 on 2023-05-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_watchlist_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='text',
            field=models.CharField(default=5, max_length=60),
            preserve_default=False,
        ),
    ]
