# Generated by Django 4.1.7 on 2023-05-29 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_watchlist_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='text',
        ),
    ]
