# Generated by Django 4.1.7 on 2023-06-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_watch_list_watchlist_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
